name: Flask CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - uses: actions/checkout@v3

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4️⃣ Optional: deploy (example)
      - name: Deploy
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DATABASE_URI: ${{ secrets.DATABASE_URI }}
        run: |
          echo "Ready to deploy your Flask app..."
